services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - my_network
    environment:
      ENV: 'DEV'
      CONFIG: ${CONFIG}
      CRYPTO_CONFIG: ${CRYPTO_CONFIG}
    ports:
      - "3001:3001"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - my_network

  db:
    image: postgres:13 #upgrade version
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "16115:5432"

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge