-- Copyright 2025 Leandro Herenu - BOS (Beauty Of Strength)
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

--cuanto se llama cada evento por usuario
select
    useraccount_id,
    event.event,
    count(1) c
from app.event
group by useraccount_id, event.event
order by c desc;

--manual account creation
insert into
    useraccount(name, username, email, emailverified, usertype, password, pictureurl, locale, accountplan_id, createddate, lastpaymentdate, trainer, code)
values('Uriel Oriana', 'urielluca00@gmail.com', 'urielluca00@gmail.com',
       true, 'p', 'autogenerated', 'https://bos.team/api/logo?invite=uriel.oriana&type=logo64.png',
       'es', 3, now(), null, null, 'uriel.oriana');
select * from useraccount where code='uriel.oriana';