--cuanto se llama cada evento por usuario
select
    useraccount_id,
    event.event,
    count(1) c
from app.event
group by useraccount_id, event.event
order by c desc;

--manual account creation
insert into
    useraccount(name, username, email, emailverified, usertype, password, pictureurl, locale, accountplan_id, createddate, lastpaymentdate, trainer, code)
values('Uriel Oriana', 'urielluca00@gmail.com', 'urielluca00@gmail.com',
       true, 'p', 'autogenerated', 'https://bos.team/api/logo?invite=uriel.oriana&type=logo64.png',
       'es', 3, now(), null, null, 'uriel.oriana');
select * from useraccount where code='uriel.oriana';